version: '3.3'

services:
  example-frontend:
    image: example-frontend
    build: ./example-frontend
    ports:
      - 5000:5000
    container_name: frontend
  
  example-backend:
    image: example-backend
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=example
    container_name: backend

  redis:
    image: redis
    container_name: redis
  
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: postgres
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    container_name: nginx

