version: '3.3'

services:
  example-frontend:
    image: example-frontend
    build: ./example-frontend
    ports:
      - 5000:5000
    container_name: frontend
  
  example-backend:
    image: example-backend
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    container_name: backend

  redis:
    image: redis
    container_name: redis