FROM node:16.14.0-alpine3.14

EXPOSE 5000

WORKDIR /usr/frontend

COPY . .

RUN npm install -g serve && \
    npm ci && \
    adduser -D appuser && \
    chown -R appuser:appuser /usr/frontend && \
    npm run build && \
    rm -Rf node_modules

USER appuser 

CMD ["serve","-s","-l","5000","build"]